sudo: required
services:
  - docker
script:
  - ./buildAndTestContainer.sh
deploy:
    provider: script
    skip_cleanup: true
    on:
        branch: master
    script: docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"; docker tag andmos/readinglist:$(git rev-parse --short HEAD) andmos/readinglist:latest; docker push andmos/readinglist:latest;
