sudo: required
services:
  - docker
before_script:
  - chmod +x build.sh
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
script:
  - docker build -t andmos/readinglist:build-$TRAVIS_BUILD_NUMBER .
  - docker run -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):/tests gcr.io/gcp-runtimes/container-structure-test:v1.2.2 test --image andmos/readinglist:build-$TRAVIS_BUILD_NUMBER --config /tests/imageTests/readinglist_container_tests_config.yaml
  - docker run --name readinglist -dt -p 1337:1337 -e APIKey=$TrelloAPIKey -e UserToken=$TrelloUserToken andmos/readinglist:build-$TRAVIS_BUILD_NUMBER
  - sleep 3
  - docker run --link readinglist:readlinglist --rm -e APIKey=$TrelloAPIKey -e UserToken=$TrelloUserToken -v $(pwd):/app graze/bats /app/batsTests
after_success:
 - if [ "$TRAVIS_BRANCH" == "master" ]; then
   docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
   docker tag andmos/readinglist:build-$TRAVIS_BUILD_NUMBER andmos/readinglist:latest
   docker push andmos/readinglist:latest;
   fi
