apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesStrategicMerge:
- environment.yaml
- replica-and-rollout-strategy.yaml
resources:
- ../../base
- route.yaml
crds:
- crds/openshift-route.json
secretGenerator:
- envs: 
  - secrets.env
  name: readinglistsecrets
  type: Opaque