apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- environment.yaml
- replica-and-rollout-strategy.yaml
resources:
- ../../base
secretGenerator:
- envs:
  - secrets.env
  name: readinglistSecrets
  type: Opaque
