apiVersion: v1
data:
  TrelloAPIKey: N2E5NmQ4MjZkYWU0NTI0Y2M5NTgwYTA0MDM2OGQ0YzI=
  TrelloUserToken: ZGY4ZDAxZTRhZGRlODdiNDYwYzc0YTNmYzQ3ZjlhZTUxY2EzNDE1NTgwZmRhZmI2YzNjY2Y2NDEyZjlkZWIxMQ==
kind: Secret
metadata:
  name: readinglistsecrets-m7d28tg2hh
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  name: readinglist
spec:
  ports:
  - port: 80
    targetPort: 1337
  selector:
    app: readinglist
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: readinglist
spec:
  replicas: 3
  selector:
    matchLabels:
      app: readinglist
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: readinglist
    spec:
      containers:
      - env:
        - name: TrelloAuthSettings__TrelloAPIKey
          valueFrom:
            secretKeyRef:
              key: TrelloAPIKey
              name: readinglistsecrets-m7d28tg2hh
        - name: TrelloAuthSettings__TrelloUserToken
          valueFrom:
            secretKeyRef:
              key: TrelloUserToken
              name: readinglistsecrets-m7d28tg2hh
        image: andmos/readinglist:carter
        name: app
        ports:
        - containerPort: 1337
          name: http
          protocol: TCP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: readinglist
  name: readinglist
spec:
  host: readinglist.apps.datest.no
  tls:
    termination: edge
  to:
    kind: Service
    name: readinglist
