schemaVersion: "2.0.0"

fileExistenceTests:
- name: 'confd'
  path: '/usr/local/bin/confd'
  shouldExist: true
- name: 'ReadingList.exe'
  path: '/ReadingList/bin/Release/ReadingList.exe'
  shouldExist: true
- name: 'ReadingList.exe.config'
  path: '/ReadingList/bin/Release/ReadingList.exe.config'
  shouldExist: true
- name: 'ReadingList.exe.config.template'
  path: '/etc/confd/templates/ReadingList.exe.config.template'
  shouldExist: true
- name: 'ReadingList.exe.config.toml'
  path: '/etc/confd/conf.d/ReadingList.exe.config.toml'
  shouldExist: true

fileContentTests:
- name: 'ReadingList.exe.config.template, APIKey'
  path: '/etc/confd/templates/ReadingList.exe.config.template'
  expectedContents: ['getenv "APIKey"']

- name: 'ReadingList.exe.config.template, UserToken'
  path: '/etc/confd/templates/ReadingList.exe.config.template'
  expectedContents: ['getenv "UserToken"']

- name: 'ReadingList.exe.config.template, HostURL'
  path: '/etc/confd/templates/ReadingList.exe.config.template'
  expectedContents: ['getenv "HostURL"']

metadataTest:
    entrypoint: ["./docker-entrypoint.sh"]
    exposedPorts: ["1337"]
