schemaVersion: "2.0.0"

fileExistenceTests:
- name: 'ReadingList.Carter.exe'
  path: '/app/ReadingList.Carter.dll'
  shouldExist: true
- name: 'appsettings.json'
  path: '/app/appsettings.json'
  shouldExist: true

fileContentTests:
- name: 'appsettings.json, TrelloAPIKey'
  path: '/app/appsettings.json'
  expectedContents: ['"TrelloAPIKey"']

- name: 'ReadingList.Carter.csproj, TrelloUserToken'
  path: '/app/appsettings.json'
  expectedContents: ['"TrelloUserToken"']

commandTests: 
- name: 'dotnet runtime version'
  command: 'dotnet'
  args: ['--list-runtimes']
  expectedOutput: ['8.0.*']

metadataTest:
    exposedPorts: ["1337"]
