schemaVersion: "2.0.0"

fileExistenceTests:
- name: 'ReadingList.Carter.exe'
  path: '/app/ReadingList.Carter.dll'
  shouldExist: true
- name: 'appsettings.json'
  path: '/app/appsettings.json'
  shouldExist: true

fileContentTests:
- name: 'appsettings.json, TrelloAPIKey'
  path: '/app/appsettings.json'
  expectedContents: ['"TrelloAPIKey"']

- name: 'ReadingList.Carter.csproj, TrelloUserToken'
  path: '/app/appsettings.json'
  expectedContents: ['"TrelloUserToken"']

metadataTest:
    exposedPorts: ["1337"]
