name: CI with nix 
on: 
  push:
  workflow_dispatch:
jobs: 
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Nix store
        run: |
          # Create with liberal rights, otherwise cache action will complain
          # about permission errors.
          sudo mkdir -p /nix/store
          sudo chmod -R 777 /nix
      - uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Build
        run: nix-build -E 'with import <nixpkgs> { }; callPackage ./default.nix { }'